#!/bin/sh

set -o errexit

flash() {
    for line in $(cat $1); do
        part_name=$(echo $line | cut -d ':' -f 1) 
        file_name=$(echo $line | cut -d ':' -f 2)
        
        dd oflag=dsync if="/opt/tegra-binaries-signed/$update_dir/$file_name" of="/dev/disk/by-partlabel/$part_name"
    done
}

flash "/opt/tegra-binaries-signed/partition_specification.txt"
